language: python
python:
    - "2.7"
sudo: false

# Cache the pip directory. "cache: pip" doesn't work due to install override.
# See https://github.com/travis-ci/travis-ci/issues/3239.
cache:
  - directories:
    - $HOME/.cache/pip
install:
    - pip install -U pip wheel
    - make requirements
script:
    - make test
branches:
    only:
        - master
