language: python
python:
    - 3.5
sudo: false

cache: pip
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
install:
    - pip install -U pip wheel codecov
    - pip install -r requirements/test.txt
script:
    - make validate
after_success:
    - codecov
